### ISSUE TITLE
Emerald Framework logo at the homepage

### ISSUE THREAD

**Issue by EdDeAlmeidaJr** [EmeraldFramework/emeraldapp#2]
![emarald select logo no2_evaldo-01](https://cloud.githubusercontent.com/assets/14207061/24231691/c581bc68-0f64-11e7-9cfa-c1e0a78d0982.png)

This is the official logo. it must be at the homepage, where the React logo is now, but is a bigger size.

**Comment by EdDeAlmeidaJr** [comment]
@khovisfersa You may modify the background color to adapt it to the logo. It is probable that the current dark background color won't work fine with it.

**Comment by khovisfersa** [comment]
@EdDeAlmeidaJr working on it. i'll upload the preview today as soon as i finish it
